## DosCard Project DosBox Module Chain MAKEFILE
## Copyright (C) 2013-2014 Soloviov Dmitry

all:
	cd src; make all
.PHONY:	all

llvm:
	cd src; make -f Makefile.llvm all
.PHONY: llvm

clean:
	cd src; make clean
