## DosCard Project DosBox Module Chain MAKEFILE
## Copyright (C) 2013-2015 Dmitry Soloviov

all:
	cd src; make all
.PHONY:	all

llvm:
	cd src; make -f Makefile.llvm all
.PHONY: llvm

mingw:
	cd src; make -f Makefile.mingw all
.PHONY: mingw

clean:
	cd src; make clean
